name: VoxelVoyage
main: com.przlabs.voyage.application.VoxelVoyage
version: 1.1.0
website: missing
author: przerwap
description: >
             Flight paths!
commands:
  voyage:
    description: VoxelVoyage command
